---

# Ansible lookup documentation: 
# http://docs.ansible.com/ansible/latest/playbooks_lookups.html
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/csvfile_lookup.html

# {{ lookup('[csvfile]', '[value_to_lookup] file=[/path/to/file.csv] delimiter=,') }}

# We have moved the credentials for hosts out of the inventory file and into a separate csv file called credentials.csv. Check it out!
# In the given playbook, the password for the host web_server is hardcoded into a variable ansible_ssh_pass.
# Replace the Ansible Password field to use "lookup" plugin to lookup a "csvfile", the file is "credentials.csv" and the value to lookup is "web_server"


-
  name: Test Connectivity
  hosts: web_server
  vars:
    ansible_ssh_pass: "{{ lookup('csvfile', 'web_server file=credentials.csv delimiter=,') }}"
  tasks:
  - name: Ping target host
    ping:
      data: "Test"