---

# Update the msg field in debug task to print - "The name is bond! james bond!"

# Ansible playbook filters for formatting data:
# Documentation: http://docs.ansible.com/ansible/latest/playbooks_filters.html#filters-for-formatting-data

# Jinja2 Docs:
# https://jinja.palletsprojects.com/


-
  name: Test Jinja2 Templating
  hosts: localhost
  vars:
    first_name: james
    last_name: bond
  tasks:
  - debug:
      msg: 'The name is {{ last_name }}! {{ first_name }} {{ last_name }}!'