---
- name: Deploy a web application
  hosts: target1

  tasks:
    - name: Install required depnendencies
      # su -
      # apt update && apt upgrade -y
      # apt-get install -y python python-setuptools python-dev build-essential python3-pip
      become: true
      become_method: su
      ansible.builtin.apt:
        name: '{{ item }}'
        state: present
      with_items:
        - python
        - python-setuptools
        - python-dev 
        - build-essential 
        - python3-pip

    - name: Install pip packages
      # su -
      # pip3 install pymysql
      # By default, Ansible will take the appropriate version for the python interpreter use by ansible, e.g. pip3 on python 3, and pip2 or pip on python 2.
      become: true
      become_method: su
      pip:
        name: pymysql
        state: present

    - name: Install MySQL database
      # apt-get install -y mysql-server mysql-client
      become: true
      become_method: su
      ansible.builtin.apt:
        name: '{{ item }}'
        state: present
      with_items:
        - mysql-server
        - mysql-client

    - name: Start MySQL Service
      # service mysql start
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create Application database
      # mysql -u <username> -p  # root/''
      # mysql> CREATE DATABASE employee_db;
      mysql_db: 
        name: employee_db
        login_user: 'root'
        login_password: ''
        state: present

    - name: Create Database user
      # mysql -u <username> -p
      # mysql> GRANT ALL ON *.* to db_user@'%' IDENTIFIED BY 'Passw0rd';
      # mysql> USE employee_db;
      # mysql> CREATE TABLE employees (name VARCHAR(20));
      mysql_user:
        name: db_user
        password: Passw0rd
        priv: '*.*:ALL'
        state: present
        host: '%'

    - name: Install Python Flask dependency
      # pip install flask
      # pip install flask-mysql
      become: true
      become_method: su
      pip:
        name: '{{ item }}'
        state: present
      with_items: 
        - flask
        - flask-mysql

    - name: Copy source code to target server
      # Copy source code file to remote host
      copy: src=app.py dest=/opt/app.py

    - name: Start Web server
      # run shell command to start flask
      shell: FLASK_APP=/opt nohup flask run --host=0.0.0.0 &    
