- name: Install Python Flask dependency
  # pip install flask
  # pip install flask-mysql
  become: true
  become_method: su
  ansible.builtin.pip:
    name: '{{ item }}'
    state: present
  with_items: 
    - flask
    - flask-mysql

- name: Copy source code to target server
  # Copy source code file to remote host
  ansible.builtin.copy: src=app.py dest=/opt/app.py

- name: Start Web server
  # run shell command to start flask
  ansible.builtin.shell: FLASK_APP=/opt nohup flask run --host=0.0.0.0 &
