---

# Ansible async documentation:
# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_async.html

- name: Monitor web app async but sequentially
  hosts: db_and_web_servers
  tasks: 
    - command: /opt/monitor_webapp.py
      # expected execution time [sec]
      async: 360
      # poll: re-check async task [sec] (default 10 sec)
      poll: 60

    # Watit until first task has finished.
    # Proceeed with second task after finished.

    - command: /opt/monitor_database.py
      # expected execution time [sec]
      async: 360
      # poll: re-check async task [sec] (default 10 sec)
      poll: 60
