---

# Asynchronous Actions - 2
##########################

## The default polling interval is 10 seconds. We think that is too often.
## Task: Change it to poll every 30 seconds.

# Ansible async documentation:
# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_async.html

-
  name: Deploy a mysql DB
  hosts: db_server
  roles:
    - python
    - mysql_db

-
  name: Deploy a Web Server
  hosts: web_server
  roles:
    - python
    - flask_web

-
  name: Monitor Web Application for 6 Minutes
  hosts: web_server
  command: /opt/monitor_webapp.py
  async: 360
  poll: 30
